"""empty message

Revision ID: 077062c9675b
Revises: 31c5eeb3b078
Create Date: 2023-11-06 08:06:01.987867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077062c9675b'
down_revision = '31c5eeb3b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
