"""empty message

Revision ID: 19e248ae1874
Revises: 25bbbffea321
Create Date: 2023-11-08 18:25:20.264731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e248ae1874'
down_revision = '25bbbffea321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_process',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('minimum_support', sa.Float(), nullable=True),
    sa.Column('minimum_confidence', sa.Float(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mining_process_id', sa.String(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mining_process_id'], ['mining_process.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_result_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_result_id', sa.Integer(), nullable=True),
    sa.Column('itemCode', sa.String(), nullable=True),
    sa.Column('is_antecedent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['association_result_id'], ['association_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itemCode'], ['products.itemCode'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_result_products')
    op.drop_table('association_results')
    op.drop_table('mining_process')
    # ### end Alembic commands ###
