"""empty message

Revision ID: 1d366762a040
Revises: 8a62b4c4b66a
Create Date: 2023-10-29 11:02:20.318650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d366762a040'
down_revision = '8a62b4c4b66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_result_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemCode', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('association_result_products_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['itemCode'], ['itemCode'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_result_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('association_result_products_product_id_fkey', 'products', ['product_id'], ['itemCode'])
        batch_op.drop_column('itemCode')

    # ### end Alembic commands ###
