"""empty message

Revision ID: 36d50df587eb
Revises: b2fa43391171
Create Date: 2023-10-31 09:11:15.577658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d50df587eb'
down_revision = 'b2fa43391171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('minimum_support', sa.Float(), nullable=True),
    sa.Column('minimum_confidence', sa.Float(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('itemCode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('itemCode')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('association_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mining_process_id', sa.Integer(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mining_process_id'], ['mining_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('itemCode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemCode'], ['products.itemCode'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_result_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_result_id', sa.Integer(), nullable=True),
    sa.Column('itemCode', sa.String(), nullable=True),
    sa.Column('is_antecedent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['association_result_id'], ['association_results.id'], ),
    sa.ForeignKeyConstraint(['itemCode'], ['products.itemCode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_result_products')
    op.drop_table('transaction_products')
    op.drop_table('association_results')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('products')
    op.drop_table('mining_process')
    # ### end Alembic commands ###
