"""empty message

Revision ID: 517438464aa3
Revises: 077062c9675b
Create Date: 2023-11-08 09:29:37.124568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517438464aa3'
down_revision = '077062c9675b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_process', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('mining_process_id_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_process', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('mining_process_id_seq'::regclass)"))

    # ### end Alembic commands ###
