"""empty message

Revision ID: 84a9f8e53f5d
Revises: 0d8f1089578f
Create Date: 2023-10-18 10:24:59.780771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a9f8e53f5d'
down_revision = '0d8f1089578f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('itemCode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemCode'], ['products.itemCode'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_products')
    op.drop_table('transactions')
    # ### end Alembic commands ###
