"""empty message

Revision ID: 9d12bc02fe43
Revises: 36d50df587eb
Create Date: 2023-10-31 09:30:23.948517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d12bc02fe43'
down_revision = '36d50df587eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_result_products', schema=None) as batch_op:
        batch_op.drop_constraint('association_result_products_itemCode_fkey', type_='foreignkey')
        batch_op.drop_constraint('association_result_products_association_result_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['itemCode'], ['itemCode'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'association_results', ['association_result_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('association_results', schema=None) as batch_op:
        batch_op.drop_constraint('association_results_mining_process_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mining_process', ['mining_process_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('association_results_mining_process_id_fkey', 'mining_process', ['mining_process_id'], ['id'])

    with op.batch_alter_table('association_result_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('association_result_products_association_result_id_fkey', 'association_results', ['association_result_id'], ['id'])
        batch_op.create_foreign_key('association_result_products_itemCode_fkey', 'products', ['itemCode'], ['itemCode'])

    # ### end Alembic commands ###
