"""empty message

Revision ID: f04105c812a1
Revises: 19e248ae1874
Create Date: 2023-12-02 15:19:26.949783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04105c812a1'
down_revision = '19e248ae1874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_products_transaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['transaction_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_products_transaction_id_fkey', 'transactions', ['transaction_id'], ['transaction_id'])

    # ### end Alembic commands ###
